
13-02-2018 10:01:54:367 - I: 	Executing process python.exe "" B "C:\Users\Dafi Faraz\Documents\GitHub\tubes1Stima\Game Engine\Replays\2018-02-13 10-01-53-907\Phase 1 - Round 0\B"
13-02-2018 10:01:54:413 - I: 	Bot calibration complete and can run an additional 55ms due to environment startup
13-02-2018 10:01:54:433 - D: 	Executing bot with following commands python.exe "bot.py" B "C:\Users\Dafi Faraz\Documents\GitHub\tubes1Stima\Game Engine\Replays\2018-02-13 10-01-53-907\Phase 1 - Round 0\B"
13-02-2018 10:01:54:433 - I: 	Executing process python.exe "bot.py" B "C:\Users\Dafi Faraz\Documents\GitHub\tubes1Stima\Game Engine\Replays\2018-02-13 10-01-53-907\Phase 1 - Round 0\B"
13-02-2018 10:01:54:435 - I: 	Bot has 4000ms to run before it will be forcefully killed
13-02-2018 10:01:54:482 - E: 	Output from bot: Traceback (most recent call last):
13-02-2018 10:01:54:482 - E: 	Output from bot:   File "bot.py", line 204, in <module>
13-02-2018 10:01:54:482 - E: 	Output from bot:     main(args.PlayerKey)
13-02-2018 10:01:54:482 - E: 	Output from bot:   File "bot.py", line 23, in main
13-02-2018 10:01:54:482 - E: 	Output from bot:     place_ships()
13-02-2018 10:01:54:482 - E: 	Output from bot:   File "bot.py", line 182, in place_ships
13-02-2018 10:01:54:482 - E: 	Output from bot:     list_ships = loadPlacingMap()
13-02-2018 10:01:54:482 - E: 	Output from bot:   File "bot.py", line 165, in loadPlacingMap
13-02-2018 10:01:54:482 - E: 	Output from bot:     file = open("Place.txt","r")
13-02-2018 10:01:54:482 - E: 	Output from bot: FileNotFoundError: [Errno 2] No such file or directory: 'Place.txt'
13-02-2018 10:01:54:498 - E: 	Output from bot: 
13-02-2018 10:01:54:498 - I: 	Output from bot: 
13-02-2018 10:01:54:498 - I: 	Your bots total execution time was 00:00:00.0671905